[package]
name = "ta-rss"
version = "0.1.0"
authors = ["Matthias Buttgereit <matthias.buttgereit@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1"
atom_syndication = "0.12"
crossterm = { version = "0.27", features = ["event-stream"] }
futures = "0.3.30"
ratatui = "0.26.0"
reqwest = { version = "0.11", features = ["blocking"] }
rss = { version = "2", features = ["atom", "atom_syndication"] }
tokio = { version = "1.35", features = ["full"] }
