[package]
name = "ta-rss"
version = "0.1.0"
authors = ["Matthias Buttgereit <matthias.buttgereit@outlook.com>"]
license = "MIT"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"
unused = "allow" # For exploratory dev.

[dependencies]
anyhow = "1.0"
atom_syndication = "0.12"
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
crossterm = { version = "0.27", features = ["event-stream"] }
futures = "0.3"
html2text = "0.12.5"
html_parser = "0.7"
image = "0.25"
open = "5.0"
ratatui = "0.26"
ratatui-image = { version = "1", features = ["crossterm"] }
reqwest = { version = "0.12", features = ["blocking"] }
rss = { version = "2.0", features = ["atom", "atom_syndication"] }
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
panic = "abort"   # Don't unwind the stack when panicking.
codegen-units = 1 # No parallel codegen units.
lto = true        # Optimize at link time.
